require "dj.options"
require "dj.keymaps"
require "dj.plugins"
require "dj.colorscheme"
require "dj.treesitter"
require "dj.telescope"
require "dj.lsp"
require "dj.cmp"
require "dj.testpopup"
require "dj.bindings"

